# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_wasmer_wrappers", use_symbols = TRUE, package_name = "wasmer")

#' @usage NULL
#' @useDynLib wasmer, .registration = TRUE
NULL

#' Create a new Wasmer runtime
#'
#' @title Create a new Wasmer runtime
#' @description Create a new Wasmer runtime for executing WebAssembly modules.
#' @family runtime management
#' @seealso [wasmer_runtime_new_with_compiler_ext()], [wasmer_runtime_release_ressources()]
#' @return External pointer to WasmerRuntime
#' @examples
#' ptr <- wasmer_runtime_new()
#' @export
wasmer_runtime_new <- function() .Call(wrap__wasmer_runtime_new)

#' Compile a WAT (WebAssembly Text) module and add it to the runtime
#'
#' @title Compile WAT module
#' @description Compile a WebAssembly Text (WAT) module and add it to the runtime.
#' @family module compilation
#' @seealso [wasmer_compile_wasm_ext()], [wasmer_wat_to_wasm_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @param wat_code WAT code as a string.
#' @param module_name Name to register the module under.
#' @return Status message
#' @examples
#' wasmer_compile_wat_ext(ptr, wat_code, "mod1")
#' @export
wasmer_compile_wat_ext <- function(ptr, wat_code, module_name) .Call(wrap__wasmer_compile_wat_ext, ptr, wat_code, module_name)

#' Compile a WASM binary and add it to the runtime
#'
#' @title Compile WASM binary
#' @description Compile a WebAssembly binary and add it to the runtime.
#' @family module compilation
#' @seealso [wasmer_compile_wat_ext()], [wasmer_wat_to_wasm_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @param wasm_bytes WASM binary as R raw vector.
#' @param module_name Name to register the module under.
#' @return Status message
#' @examples
#' wasmer_compile_wasm_ext(ptr, wasm_bytes, "mod1")
#' @export
wasmer_compile_wasm_ext <- function(ptr, wasm_bytes, module_name) .Call(wrap__wasmer_compile_wasm_ext, ptr, wasm_bytes, module_name)

#' Instantiate a compiled module in the runtime.
#' @param ptr External pointer to WasmerRuntime
#' @param module_name Name of the module to instantiate
#' @param instance_name Name to register the instance under
#' @return Status message
#' @export
wasmer_instantiate_ext <- function(ptr, module_name, instance_name) .Call(wrap__wasmer_instantiate_ext, ptr, module_name, instance_name)

#' Call an exported function from a WASM instance
#'
#' @title Call WASM function
#' @description Call an exported function from a WASM instance.
#' @family function calling
#' @seealso [wasmer_call_function_safe_ext()], [wasmer_host_function_example_ext()], [wasmer_math_example_ext()], [wasmer_hello_world_example_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @param instance_name Name of the instance.
#' @param function_name Name of the function to call.
#' @param args Arguments as R list.
#' @return List with success flag and result or error
#' @examples
#' wasmer_call_function_ext(ptr, "inst1", "add", list(1, 2))
#' @export
wasmer_call_function_ext <- function(ptr, instance_name, function_name, args) .Call(wrap__wasmer_call_function_ext, ptr, instance_name, function_name, args)

#' List all exports from a WASM instance
#'
#' @title List WASM exports
#' @description List all exports from a WASM instance.
#' @family exports and signatures
#' @seealso [wasmer_list_function_signatures_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @param instance_name Name of the instance.
#' @return List with success flag and exports or error
#' @examples
#' wasmer_list_exports_ext(ptr, "inst1")
#' @export
wasmer_list_exports_ext <- function(ptr, instance_name) .Call(wrap__wasmer_list_exports_ext, ptr, instance_name)

#' Register an R function for use as a host function in WASM (per-runtime)
#'
#' @title Register R host function
#' @description Register an R function for use as a host function in WASM (per-runtime).
#' @family host function registration
#' @seealso [wasmer_function_new_ext()], [wasmer_function_new_i32_to_i32()], [wasmer_function_new_i32_i32_to_i32()], [wasmer_function_new_f64_f64_to_f64()], [wasmer_function_new_f64_to_f64()], [wasmer_function_new_i32_to_void()], [wasmer_function_new_void_to_i32()]
#' @param ptr External pointer to WasmerRuntime.
#' @param _name Name to register the function under.
#' @param fun R function object.
#' @return TRUE if successful
#' @examples
#' wasmer_register_r_function_ext(ptr, "myfun", function(x) x)
#' @export
wasmer_register_r_function_ext <- function(ptr, name, fun) .Call(wrap__wasmer_register_r_function_ext, ptr, name, fun)

#' Math operations example
#'
#' @title Math operations example
#' @description Example WASM module for math operations.
#' @family function calling
#' @seealso [wasmer_call_function_ext()], [wasmer_call_function_safe_ext()], [wasmer_host_function_example_ext()], [wasmer_hello_world_example_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @param a First integer.
#' @param b Second integer.
#' @return List with results of add and multiply
#' @examples
#' wasmer_math_example_ext(ptr, 2, 3)
#' @export
wasmer_math_example_ext <- function(ptr, a, b) .Call(wrap__wasmer_math_example_ext, ptr, a, b)

#' Create a simple "Hello World" example
#'
#' @title Hello World example
#' @description Create a simple WASM "Hello World" example.
#' @family function calling
#' @seealso [wasmer_call_function_ext()], [wasmer_call_function_safe_ext()], [wasmer_host_function_example_ext()], [wasmer_math_example_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @return String result from WASM hello function
#' @examples
#' wasmer_hello_world_example_ext(ptr)
#' @export
wasmer_hello_world_example_ext <- function(ptr) .Call(wrap__wasmer_hello_world_example_ext, ptr)

#' Convert WAT (WebAssembly Text) to WASM binary and return as R raw vector
#'
#' @title Convert WAT to WASM
#' @description Convert WebAssembly Text (WAT) to WASM binary and return as R raw vector.
#' @family module compilation
#' @seealso [wasmer_compile_wat_ext()], [wasmer_compile_wasm_ext()]
#' @param wat_code WAT code as a string.
#' @return WASM binary as R raw vector, or error string if conversion fails
#' @examples
#' wasmer_wat_to_wasm_ext(wat_code)
#' @export
wasmer_wat_to_wasm_ext <- function(wat_code) .Call(wrap__wasmer_wat_to_wasm_ext, wat_code)

#' Create an instance with host functions for mathematical operations
#'
#' @title Instantiate WASM module with math imports
#' @description Instantiate a WASM module with host functions for mathematical operations.
#' @family module instantiation
#' @seealso [wasmer_instantiate_ext()], [wasmer_instantiate_with_table_ext()], [wasmer_wasi_state_new_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @param module_name String name of the module to instantiate.
#' @param instance_name String name to identify this instance.
#' @return Status message
#' @examples
#' wasmer_instantiate_with_math_imports_ext(ptr, "mod1", "inst1")
#' @export
wasmer_instantiate_with_math_imports_ext <- function(ptr, module_name, instance_name) .Call(wrap__wasmer_instantiate_with_math_imports_ext, ptr, module_name, instance_name)

#' Advanced function calling with type safety
#'
#' @title Call WASM function (type safe)
#' @description Call an exported WASM function with type safety and conversion.
#' @family function calling
#' @seealso [wasmer_call_function_ext()], [wasmer_host_function_example_ext()], [wasmer_math_example_ext()], [wasmer_hello_world_example_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @param instance_name String name of the instance.
#' @param function_name String name of the function to call.
#' @param args List of arguments with proper type conversion.
#' @return List with success flag and result or error
#' @examples
#' wasmer_call_function_safe_ext(ptr, "inst1", "add", list(1, 2))
#' @export
wasmer_call_function_safe_ext <- function(ptr, instance_name, function_name, args) .Call(wrap__wasmer_call_function_safe_ext, ptr, instance_name, function_name, args)

#' Example with host function imports
#'
#' @title Host function example
#' @description Example with host function imports.
#' @family function calling
#' @seealso [wasmer_call_function_ext()], [wasmer_call_function_safe_ext()], [wasmer_math_example_ext()], [wasmer_hello_world_example_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @return List with results
#' @examples
#' wasmer_host_function_example_ext(ptr)
#' @export
wasmer_host_function_example_ext <- function(ptr) .Call(wrap__wasmer_host_function_example_ext, ptr)

#' List exported function signatures (name, input types, output types) for a WASM instance
#'
#' @title List WASM function signatures
#' @description List exported function signatures (name, input types, output types) for a WASM instance.
#' @family exports and signatures
#' @seealso [wasmer_list_exports_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @param instance_name Name of the instance.
#' @return Data frame with columns: name, params, results
#' @examples
#' wasmer_list_function_signatures_ext(ptr, "inst1")
#' @export
wasmer_list_function_signatures_ext <- function(ptr, instance_name) .Call(wrap__wasmer_list_function_signatures_ext, ptr, instance_name)

#' Get the size of exported memory (in bytes and pages)
#'
#' @title Get WASM memory size
#' @description Get the size of exported memory (in bytes and pages).
#' @family memory operations
#' @seealso [wasmer_memory_read_ext()], [wasmer_memory_write_ext()], [wasmer_memory_read_string_ext()], [wasmer_memory_grow_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @param instance_name Name of the instance.
#' @param memory_name Name of the exported memory (default "memory").
#' @return List with size_bytes and size_pages
#' @examples
#' wasmer_memory_size_ext(ptr, "inst1", "memory")
#' @export
wasmer_memory_size_ext <- function(ptr, instance_name, memory_name) .Call(wrap__wasmer_memory_size_ext, ptr, instance_name, memory_name)

#' Read bytes from WASM memory
#'
#' @title Read WASM memory
#' @description Read bytes from WASM memory.
#' @family memory operations
#' @seealso [wasmer_memory_size_ext()], [wasmer_memory_write_ext()], [wasmer_memory_read_string_ext()], [wasmer_memory_grow_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @param instance_name Name of the instance.
#' @param memory_name Name of the exported memory.
#' @param offset Offset to start reading.
#' @param length Number of bytes to read.
#' @return Raw vector of bytes
#' @examples
#' wasmer_memory_read_ext(ptr, "inst1", "memory", 0, 10)
#' @export
wasmer_memory_read_ext <- function(ptr, instance_name, memory_name, offset, length) .Call(wrap__wasmer_memory_read_ext, ptr, instance_name, memory_name, offset, length)

#' Write bytes to WASM memory
#'
#' @title Write WASM memory
#' @description Write bytes to WASM memory.
#' @family memory operations
#' @seealso [wasmer_memory_size_ext()], [wasmer_memory_read_ext()], [wasmer_memory_read_string_ext()], [wasmer_memory_grow_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @param instance_name Name of the instance.
#' @param memory_name Name of the exported memory.
#' @param offset Offset to start writing.
#' @param bytes Raw vector of bytes to write.
#' @return TRUE if successful
#' @examples
#' wasmer_memory_write_ext(ptr, "inst1", "memory", 0, as.raw(c(1,2,3)))
#' @export
wasmer_memory_write_ext <- function(ptr, instance_name, memory_name, offset, bytes) .Call(wrap__wasmer_memory_write_ext, ptr, instance_name, memory_name, offset, bytes)

#' Read UTF-8 string from WASM memory
#'
#' @title Read WASM memory as string
#' @description Read UTF-8 string from WASM memory.
#' @family memory operations
#' @seealso [wasmer_memory_size_ext()], [wasmer_memory_read_ext()], [wasmer_memory_write_ext()], [wasmer_memory_grow_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @param instance_name Name of the instance.
#' @param memory_name Name of the exported memory.
#' @param offset Offset to start reading.
#' @param length Number of bytes to read.
#' @return String
#' @examples
#' wasmer_memory_read_string_ext(ptr, "inst1", "memory", 0, 10)
#' @export
wasmer_memory_read_string_ext <- function(ptr, instance_name, memory_name, offset, length) .Call(wrap__wasmer_memory_read_string_ext, ptr, instance_name, memory_name, offset, length)

#' Grow WASM memory by a number of pages
#'
#' @title Grow WASM memory
#' @description Grow WASM memory by a number of pages.
#' @family memory operations
#' @seealso [wasmer_memory_size_ext()], [wasmer_memory_read_ext()], [wasmer_memory_write_ext()], [wasmer_memory_read_string_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @param instance_name Name of the instance.
#' @param memory_name Name of the exported memory.
#' @param pages Number of pages to grow.
#' @return TRUE if successful
#' @examples
#' wasmer_memory_grow_ext(ptr, "inst1", "memory", 1)
#' @export
wasmer_memory_grow_ext <- function(ptr, instance_name, memory_name, pages) .Call(wrap__wasmer_memory_grow_ext, ptr, instance_name, memory_name, pages)

#' Create a new WASM Table
#'
#' @title Create WASM Table
#' @description Create a new WASM Table.
#' @family table operations
#' @seealso [wasmer_table_set_ext()], [wasmer_table_grow_ext()], [wasmer_table_get_ext()], [wasmer_get_exported_table_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @param min Minimum size.
#' @param max Maximum size (optional).
#' @return External pointer to Table
#' @examples
#' wasmer_table_new_ext(ptr, 1, 10)
#' @export
wasmer_table_new_ext <- function(ptr, min, max) .Call(wrap__wasmer_table_new_ext, ptr, min, max)

#' Set a function reference in a WASM Table
#'
#' @title Set WASM Table entry
#' @description Set a function reference in a WASM Table.
#' @family table operations
#' @seealso [wasmer_table_new_ext()], [wasmer_table_grow_ext()], [wasmer_table_get_ext()], [wasmer_get_exported_table_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @param table_ptr External pointer to Table.
#' @param index Index to set.
#' @param func_ptr External pointer to Function.
#' @return TRUE if successful
#' @examples
#' wasmer_table_set_ext(ptr, table_ptr, 0, func_ptr)
#' @export
wasmer_table_set_ext <- function(ptr, table_ptr, index, func_ptr) .Call(wrap__wasmer_table_set_ext, ptr, table_ptr, index, func_ptr)

#' Grow a WASM Table
#'
#' @title Grow WASM Table
#' @description Grow a WASM Table by a number of elements.
#' @family table operations
#' @seealso [wasmer_table_new_ext()], [wasmer_table_set_ext()], [wasmer_table_get_ext()], [wasmer_get_exported_table_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @param table_ptr External pointer to Table.
#' @param delta Number of elements to grow.
#' @param func_ptr External pointer to Function to fill new slots.
#' @return Previous size
#' @examples
#' wasmer_table_grow_ext(ptr, table_ptr, 1, func_ptr)
#' @export
wasmer_table_grow_ext <- function(ptr, table_ptr, delta, func_ptr) .Call(wrap__wasmer_table_grow_ext, ptr, table_ptr, delta, func_ptr)

#' Get a function reference from a WASM Table
#'
#' @title Get WASM Table entry
#' @description Get a function reference from a WASM Table.
#' @family table operations
#' @seealso [wasmer_table_new_ext()], [wasmer_table_set_ext()], [wasmer_table_grow_ext()], [wasmer_get_exported_table_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @param table_ptr External pointer to Table.
#' @param index Index to get.
#' @return External pointer to Function (or NULL)
#' @examples
#' wasmer_table_get_ext(ptr, table_ptr, 0)
#' @export
wasmer_table_get_ext <- function(ptr, table_ptr, index) .Call(wrap__wasmer_table_get_ext, ptr, table_ptr, index)

#' Create a Wasmer host function from an R function with dynamic signature
#'
#' @title Create dynamic R host function
#' @description Create a Wasmer host function from an R function with dynamic signature.
#' @family host function registration
#' @seealso [wasmer_register_r_function_ext()], [wasmer_function_new_i32_to_i32()], [wasmer_function_new_i32_i32_to_i32()], [wasmer_function_new_f64_f64_to_f64()], [wasmer_function_new_f64_to_f64()], [wasmer_function_new_i32_to_void()], [wasmer_function_new_void_to_i32()]
#' @param ptr External pointer to WasmerRuntime.
#' @param rfun R function object.
#' @param arg_types Character vector of argument types (e.g. c("i32", "f64")).
#' @param ret_types Character vector of return types (e.g. c("i32")).
#' @param _name Character string for registry name.
#' @return External pointer to Function
#' @examples
#' wasmer_function_new_ext(ptr, function(x) x, c("i32"), c("i32"), "myfun")
#' @export
wasmer_function_new_ext <- function(ptr, rfun, arg_types, ret_types, `_name`) .Call(wrap__wasmer_function_new_ext, ptr, rfun, arg_types, ret_types, `_name`)

#' Get a pointer to an exported table from a WASM instance by name
#'
#' @title Get exported WASM Table
#' @description Get a pointer to an exported table from a WASM instance by name.
#' @family table operations
#' @seealso [wasmer_table_new_ext()], [wasmer_table_set_ext()], [wasmer_table_grow_ext()], [wasmer_table_get_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @param instance_name Name of the instance.
#' @param table_export_name Name of the exported table.
#' @return External pointer to Table, or NULL if not found
#' @examples
#' wasmer_get_exported_table_ext(ptr, "inst1", "table1")
#' @export
wasmer_get_exported_table_ext <- function(ptr, instance_name, table_export_name) .Call(wrap__wasmer_get_exported_table_ext, ptr, instance_name, table_export_name)

#' Create a WASM host function with signature i32 -> i32
#'
#' @title Create host function (i32 -> i32)
#' @description Create a WASM host function that takes an i32 and returns an i32, using an R function as the implementation.
#' @family host function registration
#' @seealso [wasmer_register_r_function_ext()], [wasmer_function_new_ext()], [wasmer_function_new_i32_i32_to_i32()], [wasmer_function_new_f64_f64_to_f64()], [wasmer_function_new_f64_to_f64()], [wasmer_function_new_i32_to_void()], [wasmer_function_new_void_to_i32()]
#' @examples
#' wasmer_function_new_i32_to_i32(ptr, function(x) x)
#' @export
wasmer_function_new_i32_to_i32 <- function(ptr, rfun) .Call(wrap__wasmer_function_new_i32_to_i32, ptr, rfun)

#' Create a WASM host function with signature (i32, i32) -> i32
#'
#' @title Create host function ((i32, i32) -> i32)
#' @description Create a WASM host function that takes two i32 arguments and returns an i32, using an R function as the implementation.
#' @family host function registration
#' @seealso [wasmer_register_r_function_ext()], [wasmer_function_new_ext()], [wasmer_function_new_i32_to_i32()], [wasmer_function_new_f64_f64_to_f64()], [wasmer_function_new_f64_to_f64()], [wasmer_function_new_i32_to_void()], [wasmer_function_new_void_to_i32()]
#' @examples
#' wasmer_function_new_i32_i32_to_i32(ptr, function(x, y) x + y)
#' @export
wasmer_function_new_i32_i32_to_i32 <- function(ptr, rfun) .Call(wrap__wasmer_function_new_i32_i32_to_i32, ptr, rfun)

#' Create a WASM host function with signature (f64, f64) -> f64
#'
#' @title Create host function ((f64, f64) -> f64)
#' @description Create a WASM host function that takes two f64 arguments and returns an f64, using an R function as the implementation.
#' @family host function registration
#' @seealso [wasmer_register_r_function_ext()], [wasmer_function_new_ext()], [wasmer_function_new_i32_to_i32()], [wasmer_function_new_i32_i32_to_i32()], [wasmer_function_new_f64_to_f64()], [wasmer_function_new_i32_to_void()], [wasmer_function_new_void_to_i32()]
#' @examples
#' wasmer_function_new_f64_f64_to_f64(ptr, function(x, y) x * y)
#' @export
wasmer_function_new_f64_f64_to_f64 <- function(ptr, rfun) .Call(wrap__wasmer_function_new_f64_f64_to_f64, ptr, rfun)

#' Create a WASM host function with signature f64 -> f64
#'
#' @title Create host function (f64 -> f64)
#' @description Create a WASM host function that takes an f64 and returns an f64, using an R function as the implementation.
#' @family host function registration
#' @seealso [wasmer_register_r_function_ext()], [wasmer_function_new_ext()], [wasmer_function_new_i32_to_i32()], [wasmer_function_new_i32_i32_to_i32()], [wasmer_function_new_f64_f64_to_f64()], [wasmer_function_new_i32_to_void()], [wasmer_function_new_void_to_i32()]
#' @examples
#' wasmer_function_new_f64_to_f64(ptr, function(x) sqrt(x))
#' @export
wasmer_function_new_f64_to_f64 <- function(ptr, rfun) .Call(wrap__wasmer_function_new_f64_to_f64, ptr, rfun)

#' Create a WASM host function with signature i32 -> void
#'
#' @title Create host function (i32 -> void)
#' @description Create a WASM host function that takes an i32 and returns nothing, using an R function as the implementation.
#' @family host function registration
#' @seealso [wasmer_register_r_function_ext()], [wasmer_function_new_ext()], [wasmer_function_new_i32_to_i32()], [wasmer_function_new_i32_i32_to_i32()], [wasmer_function_new_f64_f64_to_f64()], [wasmer_function_new_f64_to_f64()], [wasmer_function_new_void_to_i32()]
#' @examples
#' wasmer_function_new_i32_to_void(ptr, function(x) cat(x))
#' @export
wasmer_function_new_i32_to_void <- function(ptr, rfun) .Call(wrap__wasmer_function_new_i32_to_void, ptr, rfun)

#' Create a WASM host function with signature void -> i32
#'
#' @title Create host function (void -> i32)
#' @description Create a WASM host function that takes no arguments and returns an i32, using an R function as the implementation.
#' @family host function registration
#' @seealso [wasmer_register_r_function_ext()], [wasmer_function_new_ext()], [wasmer_function_new_i32_to_i32()], [wasmer_function_new_i32_i32_to_i32()], [wasmer_function_new_f64_f64_to_f64()], [wasmer_function_new_f64_to_f64()], [wasmer_function_new_i32_to_void()]
#' @examples
#' wasmer_function_new_void_to_i32(ptr, function() 42)
#' @export
wasmer_function_new_void_to_i32 <- function(ptr, rfun) .Call(wrap__wasmer_function_new_void_to_i32, ptr, rfun)

#' Create a new Wasmer runtime with a specific compiler
#'
#' @title Create a new Wasmer runtime with a specific compiler
#' @description Create a new Wasmer runtime for executing WebAssembly modules using a specified compiler backend.
#' @family runtime management
#' @seealso [wasmer_runtime_new()], [wasmer_runtime_release_ressources()]
#' @param compiler_name Name of the compiler ("cranelift", "singlepass").
#' @return External pointer to WasmerRuntime
#' @examples
#' ptr <- wasmer_runtime_new_with_compiler_ext("cranelift")
#' @export
wasmer_runtime_new_with_compiler_ext <- function(compiler_name) .Call(wrap__wasmer_runtime_new_with_compiler_ext, compiler_name)

#' Instantiate a compiled module in the runtime, with a custom table import
#'
#' @title Instantiate WASM module with table import
#' @description Instantiate a compiled WASM module in the runtime, with a custom table import.
#' @family module instantiation
#' @seealso [wasmer_instantiate_ext()], [wasmer_instantiate_with_math_imports_ext()], [wasmer_wasi_state_new_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @param module_name Name of the module to instantiate.
#' @param instance_name Name to register the instance under.
#' @param table_ptr External pointer to Table to import as "env.host_table".
#' @return Status message
#' @examples
#' wasmer_instantiate_with_table_ext(ptr, "mod1", "inst1", table_ptr)
#' @export
wasmer_instantiate_with_table_ext <- function(ptr, module_name, instance_name, table_ptr) .Call(wrap__wasmer_instantiate_with_table_ext, ptr, module_name, instance_name, table_ptr)

#' Create a WASI or WASIX state for the runtime
#'
#' @title Create WASI/WASIX state
#' @description Create a WASI or WASIX state for the runtime.
#' @family module instantiation
#' @seealso [wasmer_instantiate_ext()], [wasmer_instantiate_with_math_imports_ext()], [wasmer_instantiate_with_table_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @param module_name Name of the module (for WASI/WASIX args).
#' @param env_type Environment type: "wasi" (default) or "wasix".
#' @return TRUE if successful, FALSE otherwise
#' @examples
#' wasmer_wasi_state_new_ext(ptr, "mod1", "wasi")
#' @export
wasmer_wasi_state_new_ext <- function(ptr, module_name, env_type) .Call(wrap__wasmer_wasi_state_new_ext, ptr, module_name, env_type)

#' Release resources held by the Wasmer runtime
#'
#' @title Release Wasmer runtime resources
#' @description Explicitly shutdown the runtime, free resources, and clear the R external pointer.
#' @family runtime management
#' @seealso [wasmer_runtime_new()], [wasmer_runtime_new_with_compiler_ext()]
#' @param ptr External pointer to WasmerRuntime.
#' @return NULL (invisible)
#' @examples
#' wasmer_runtime_release_ressources(ptr)
#' @export
wasmer_runtime_release_ressources <- function(ptr) invisible(.Call(wrap__wasmer_runtime_release_ressources, ptr))


# nolint end
