# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_wasmer_wrappers", use_symbols = TRUE, package_name = "wasmer")

#' @usage NULL
#' @useDynLib wasmer, .registration = TRUE
NULL

#' Create a new Wasmer runtime for R. Returns an external pointer to the runtime object.
#' @return External pointer to WasmerRuntime
#' @export
wasmer_runtime_new <- function() .Call(wrap__wasmer_runtime_new)

#' Compile a WAT (WebAssembly Text) module and add it to the runtime.
#' @param ptr External pointer to WasmerRuntime
#' @param wat_code WAT code as a string
#' @param module_name Name to register the module under
#' @return Status message
#' @export
wasmer_compile_wat_ext <- function(ptr, wat_code, module_name) .Call(wrap__wasmer_compile_wat_ext, ptr, wat_code, module_name)

#' Compile a WASM binary and add it to the runtime.
#' @param ptr External pointer to WasmerRuntime
#' @param wasm_bytes WASM binary as R raw vector
#' @param module_name Name to register the module under
#' @return Status message
#' @export
wasmer_compile_wasm_ext <- function(ptr, wasm_bytes, module_name) .Call(wrap__wasmer_compile_wasm_ext, ptr, wasm_bytes, module_name)

#' Instantiate a compiled module in the runtime.
#' @param ptr External pointer to WasmerRuntime
#' @param module_name Name of the module to instantiate
#' @param instance_name Name to register the instance under
#' @return Status message
#' @export
wasmer_instantiate_ext <- function(ptr, module_name, instance_name) .Call(wrap__wasmer_instantiate_ext, ptr, module_name, instance_name)

#' Call an exported function from a WASM instance.
#' @param ptr External pointer to WasmerRuntime
#' @param instance_name Name of the instance
#' @param function_name Name of the function to call
#' @param args Arguments as R list
#' @return List with success flag and result or error
#' @export
wasmer_call_function_ext <- function(ptr, instance_name, function_name, args) .Call(wrap__wasmer_call_function_ext, ptr, instance_name, function_name, args)

#' List all exports from a WASM instance.
#' @param ptr External pointer to WasmerRuntime
#' @param instance_name Name of the instance
#' @return List with success flag and exports or error
#' @export
wasmer_list_exports_ext <- function(ptr, instance_name) .Call(wrap__wasmer_list_exports_ext, ptr, instance_name)

#' Register an R function for use as a host function in WASM (per-runtime)
#' @param ptr External pointer to WasmerRuntime
#' @param name Name to register the function under
#' @param fun R function object
#' @return TRUE if successful
#' @export
wasmer_register_r_function_ext <- function(ptr, name, fun) .Call(wrap__wasmer_register_r_function_ext, ptr, name, fun)

#' Math operations example
#' @param runtime External pointer to WasmerRuntime
#' @param a First integer
#' @param b Second integer
#' @return List with results of add and multiply
#' @export
wasmer_math_example_ext <- function(ptr, a, b) .Call(wrap__wasmer_math_example_ext, ptr, a, b)

#' Create a simple "Hello World" example
#' @param runtime External pointer to WasmerRuntime
#' @return String result from WASM hello function
#' @export
wasmer_hello_world_example_ext <- function(ptr) .Call(wrap__wasmer_hello_world_example_ext, ptr)

#' Convert WAT (WebAssembly Text) to WASM binary and return as R raw vector
#' @param wat_code WAT code as a string
#' @return WASM binary as R raw vector, or error string if conversion fails
#' @export
wasmer_wat_to_wasm_ext <- function(wat_code) .Call(wrap__wasmer_wat_to_wasm_ext, wat_code)

#' Create an instance with host functions for mathematical operations
#' @param runtime External pointer to WasmerRuntime
#' @param module_name String name of the module to instantiate
#' @param instance_name String name to identify this instance
#' @return Status message
#' @export
wasmer_instantiate_with_math_imports_ext <- function(ptr, module_name, instance_name) .Call(wrap__wasmer_instantiate_with_math_imports_ext, ptr, module_name, instance_name)

#' Advanced function calling with type safety
#' @param runtime External pointer to WasmerRuntime
#' @param instance_name String name of the instance
#' @param function_name String name of the function to call
#' @param args List of arguments with proper type conversion
#' @return List with success flag and result or error
#' @export
wasmer_call_function_safe_ext <- function(ptr, instance_name, function_name, args) .Call(wrap__wasmer_call_function_safe_ext, ptr, instance_name, function_name, args)

#' Example with host function imports
#' @param runtime External pointer to WasmerRuntime
#' @return List with results
#' @export
wasmer_host_function_example_ext <- function(ptr) .Call(wrap__wasmer_host_function_example_ext, ptr)

#' List exported function signatures (name, input types, output types) for a WASM instance
#' @param ptr External pointer to WasmerRuntime
#' @param instance_name Name of the instance
#' @return Data frame with columns: name, params, results
#' @export
wasmer_list_function_signatures_ext <- function(ptr, instance_name) .Call(wrap__wasmer_list_function_signatures_ext, ptr, instance_name)

#' Get the size of exported memory (in bytes and pages)
#' @param ptr External pointer to WasmerRuntime
#' @param instance_name Name of the instance
#' @param memory_name Name of the exported memory (default "memory")
#' @return List with size_bytes and size_pages
#' @export
wasmer_memory_size_ext <- function(ptr, instance_name, memory_name) .Call(wrap__wasmer_memory_size_ext, ptr, instance_name, memory_name)

#' Read bytes from WASM memory
#' @param ptr External pointer to WasmerRuntime
#' @param instance_name Name of the instance
#' @param memory_name Name of the exported memory
#' @param offset Offset to start reading
#' @param length Number of bytes to read
#' @return Raw vector of bytes
#' @export
wasmer_memory_read_ext <- function(ptr, instance_name, memory_name, offset, length) .Call(wrap__wasmer_memory_read_ext, ptr, instance_name, memory_name, offset, length)

#' Write bytes to WASM memory
#' @param ptr External pointer to WasmerRuntime
#' @param instance_name Name of the instance
#' @param memory_name Name of the exported memory
#' @param offset Offset to start writing
#' @param bytes Raw vector of bytes to write
#' @return TRUE if successful
#' @export
wasmer_memory_write_ext <- function(ptr, instance_name, memory_name, offset, bytes) .Call(wrap__wasmer_memory_write_ext, ptr, instance_name, memory_name, offset, bytes)

#' Read UTF-8 string from WASM memory
#' @param ptr External pointer to WasmerRuntime
#' @param instance_name Name of the instance
#' @param memory_name Name of the exported memory
#' @param offset Offset to start reading
#' @param length Number of bytes to read
#' @return String
#' @export
wasmer_memory_read_string_ext <- function(ptr, instance_name, memory_name, offset, length) .Call(wrap__wasmer_memory_read_string_ext, ptr, instance_name, memory_name, offset, length)

#' Grow WASM memory by a number of pages
#' @param ptr External pointer to WasmerRuntime
#' @param instance_name Name of the instance
#' @param memory_name Name of the exported memory
#' @param pages Number of pages to grow
#' @return TRUE if successful
#' @export
wasmer_memory_grow_ext <- function(ptr, instance_name, memory_name, pages) .Call(wrap__wasmer_memory_grow_ext, ptr, instance_name, memory_name, pages)


# nolint end
